version: '3.3'
services:
  <service name>:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "1024:8000"
    restart: always
    container_name: <container name>
    image: image_name:tag
