services:
  <service name>:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1024:8000"
    restart: always
    container_name: <container_name>
    image: <image_name>:tag
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.25'
          memory: '256M'
